# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todo-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://todoblue.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_14db5a4b04b84d04a54406372121b1e5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_80324162d96245c497c8ce1b0d97f1f6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./server
        push: true
        tags: todoblue.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_14db5a4b04b84d04a54406372121b1e5 }}/todo-server:${{ github.sha }}
        file: ./server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b41df8c467b407691a3da34913f85be }}
        images: 'todoblue.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_14db5a4b04b84d04a54406372121b1e5 }}/todo-server:${{ github.sha }}'